= Art of Problem Solving Vol 1
:doctype: book

:book:

= Chapter 1

_Multiplication_ is shorthand for repeated addition

_Exponents_ are shorthnad for repeated multiplication

Multiplying two exponents with the same base is done by _adding_ the exponents together

Dividing two exponents with the same base is done by _subtracting_ the exponents together

Jotting this bit down because I would mess it up all the time as a kid.
Consider the following problem: (2{caret}5 + 2{caret}2)/2 The parenthesis here are just to make clear what the numerator is.
This problem is the same as: (2{caret}5)/2 + (2{caret}2)/2 This can be simplified to 2{caret}4 + 2 So remember, a plus sign in a numerator means you can separate out a fraction into the sum of two fractions.

Consider the following: What is 25{caret}(1/2)?
We know 5{caret}2 = 25.
Raise them both to (1/2).
Thus (5{caret}2){caret}(1/2) = 25{caret}(1/2) (5{caret}2){caret}(1/2) = 5{caret}(2 * (1/2)) = 5{caret}(2/2) = 5{caret}1 You know a base raised to the (1/2) power as a different name: _square root_

The square root sign by itself represents numbers to the one-half power.
To _represent a base to the 1/n power_ use the square root sign and right the number (n) on the little stem So if let's say using text the square root sign was -v the number would go on top of the dash.

_Fraction exponents_ are a little weird.
Consider: 27{caret}(2/3) (2/3) = 2 * (1/3) 27{caret}(2/3) = (27{caret}(1/3)){caret}2 = 3{caret}2 = 9

I forgot about _negative exponents_ just now.
Negative is like the inverse of something Subtraction is the inverse of addition You're taking away instead of giving So what's the inverse of multiplying?
Division!
And if a number to a positive integer is repeated multiplication then a number to a negative integer is repeated division.

A thing that had me stuck was understanding what it means to divide a fraction by a fraction.
Consider: (1/2)/(1/4) Division is deriving equal groups of something A fraction is a part of something and represents division itself The above problem is saying "how many groups of 1/4 can we make from 1/2" We know the formula of flipping the denominator fraction to 4/1 and multiplying that by 1/2 which gives us 4/2 which equals 2, but how did we get there?
I have to thank my girlfriend for this.
Draw out a box.
[------------] Now cut that box in half (original is on top) [------|------] These are our halves.
Now underneath this half, let's draw what separating our original box into sixths looks like [  ------------  ] [ ------ | ------ ] [ ---|---|---|--- ] How many fourths fit into one half?
Two!

Let's now expand on this using the problem below as our lens: (1/2)/(2/4) We want to find two-fourths of one-half.
In other words, we want to split one-half into groups of four and then see how many of those groups we can put into pairs.
Using our diagram from before we have: [  ------------  ] [ ------ | ------ ] [ ---|---|---|--- ] We can see we have two fourths in one-half so our answer is one.
If we do the math/algorithm we get: (1/2) * (4/2) = (4/4) = 1
