:doctype: book

:course:design:

= Design for Developers

From FrontEndMasters with Sarah Drasner

= Intro

Starts off with the idea that learning outside of a field helps you make connections faster.
A way of debunking the left vs right brain separation.

_Not a replacement for design school_ Things can be entire courses themselves So think of this as a primer and overview of the major points to develop a foundation

== Project Setup

Sarah presents a three directory structure: - insp: (inspiration) - src: actual images and fonts - dev: maybe a CLI tool to create or manipulate assets

She also mentions this should be used for helping out side projects To bring it from concept to full execution

There's the acknowledgement of things are going to be messy at first, but that's okay and it's all a part of the learning process.
Quote from a book on Art and Fear about a studio where the professor grades quantity separately from quality but the people who produced the highest quality were also those who produced the highest quantity.

= Layout

Layout and grids help us to find things, compartementalize, and problem solve.
You can come a long way by just working with grids/layout without images/typography/etc.

== Symmetry

One trick you can do is create an idea of symmetry but break it in an area.
The eye will naturally go to what breaks the symmetry.
The pitfall of symmetry is that despite looking nice it cna make things look flat and boring/basic.

== Asymmetry

Harder to get right.

Rule of Thirds Take a composition, break it down into three pieces, place the main point in one of those areas

Triad Compositions

== Shapes

Circles draw your eye more than other shapes Saccade: the eye creatin ga spacial or mental map of what you see There is said that even with still images the eye still moves around This stems from our evolution of being on the lookout for predators

For some odd reason, circles seem not aligned with other shapes when, in fact, they are

Diagonals are said to be "dynamic" and cause things to "pop"

== Recommended Book

"Making and Breaking the Grid"

Anchoring: Taking elements and laying them out to a specific line

The architecture of "space"

== Tools

* Photoshop: jpegs, fancy effects
* Illustrator: vector graphics, svgs, shapes
* Sketch: new comer, really good at having all concepts/designs in one place without slowing down

Use Illustrator for exporting icons/vector images

Think of them as JS frameworks, they'll all get the same job done, but in different ways
