= Docker

:docker:

Docker is a tool for managing containers.

A _container_ is a running process from an image.
An _image_ is a collection of layers.
A _layer_ is a set of file changes.
The overall flow is: OS \-> Layer(s) \-> Image \-> Container

== Problems and Solutions

### Linux - "cannot connect to the Docker daemon" The error looks like this: ERRO[0000] failed to dial gRPC: cannot connect to the Docker daemon.
Is 'docker daemon' running on this host?: dial unix /var/run/docker.sock: connect: no such file or directory error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=xppvzl7662a4o9r51badkyo1n&shmsize=0&target=&ulimits=null&version=1: context canceled

This error is due to a missing file (/var/run/docker.sock).
Now how do you create this file?
Through the docker service!

I know what you're thinking, "Great!
So helpful!
Much wow!" It's like running a program that creates a config file that's needed to run other scripts.
Like npm!!!
If you don't have a `package.json` file then running `npm run <your-script>` will absolutely fail.
So to get around it you need to create `package.json` which you can do with `npm init`.
The analogy falls short since you can manually create the file, but you know what I mean.

So, what's needed to create the file?
What needs to be run?
`sudo systemctl start docker` (This works for Manjaro and anything using _systemd_)

=== Opening a Docker port to share with the world (Linux)

The xref:docker-in-practice.adoc[Docker in Practice] book, in chapter 2 section 2.2 technique 1, mentions this command to allow others with access to your host machine access to docker running on that machine: `sudo docker daemon -H tcp://0.0.0.0:2375` This did not work.

To get it working on Linux (Manjaro) I had to stop all running instances of docker using `sudo systemctl stop docker` and then run the above command with `dockerd` instead of `docker daemon`.
So the command became `sudo dockerd -H tcp://0.0.0.0:2375` This runs the docker daemon locally, not through a service manager.
Makes me wonder how to do so on macOS though\....

== Learning with Jonathan

I've been going through the book link:docker-in-practice[Docker In Practice] with Jonathan.
He's been wonderful in helping me learn and understand docker.
Here are some things I learned from him: - Each step in a docker file is a layer - Within a docker file, you can break a long line into multiple lines using `\` at the end of the line - It is fine to use `&&` to group several commands together - Each step produces a cache to be used on subsequent builds - If a step changes and requires a new build, not from cache, it causes the subsequent steps to change too - (This was brought up from August and supported by Jonathan) It's better to put steps whose results may change most frequently at the end to prevent cache-busting on subsequent steps

This one item is getting its own paragraph because there are other related items to it and the whole context took me a while to understand.
Docker is stateless.
What does stateless mean?
How can a container/server be stateless?
To answer this, let's first explore what does _state_ mean in the context of a server/vm.
State infers history.
Before and after.
Think about state in terms of programming.
Think about functional programming!
Functions do not have state.
State implies some change is persisted in the surrounding context.
Something is changed and that change is persisted.
For servers/containers/vms state is considered the files on the machine.
Say the the container is up and running.
It has a set of files already there from running the build.
The _files that the image is set up with_, bootloaded with, is considered its _state_.
A change to state would then be a new file or a change to one of the files.
A _stateful_ server/container/vm would be one where if the vm was stopped after the file change and restarted, the change would still be there.
A _stateless_ server/container/vm would not have the change.
It would be back to its original files.
A total fresh vm.
