:doctype: book

:jeopardy:stupid:

= For Jeopardy

Your going to hate me: - Q: What color is "the dress"?
- Q: Which of the fast food chains is the best?
A: None, they're all garbage - Q: Name a NON-EUROPEAN country that ends with two consonants.
A: Bangladesh, Egypt, Swaziland, Thailand, New Zealand, the Solomon Islands, the Ivory Coast, and the Marshall Islands.
- Q: Where's Waldo?
- Q: How many marbles are in the jar?
(don't put a picture) A: 2

Fun with numbers: - Q: What's the naughtiest number of them all?
A: 69 - Q: What are the first six digits of Pi?
A: 3.14159 - Q: What is (69 in binary) in decimal?
- Q: What number is spelled with the same number of letters as itself?
A: Four - Q: There Are More Ways to Arrange a _____ Than There Are Atoms on Earth A: deck of cards

I like to sniff paint (art): - Q: Starry Night - Van Gogh - Q: The Fountain - DuChamp - Q: Impression Sunrise - Monet - Q: Saturn Devouring His Son - Francisco Goya - Q: Yer Baby!
- Ringo Starr

Alcohol: - Q: What spirit can be made of potato, quinoia, or whey (alongside many other ingrdients) A: Vodka - Q: What is the "alcohol" in alcoholic beverages?
A: Ethanol - Q: An aromatized, fortified wine flavored with botanicals A: Vermouth - Q: Absinthe is extracted from what?
A: Wormwood - Q: What is the umbrella category for drinks such as Montenegro (not the cocktail), Averna, Aperol?
A: Amaro

Religious/Mythological Figures: - Q: The white-washed rocker of Birkenstocks before they were "cool" whose name was used to start many a holy war A: Jesus - Q: Some people call this big Poppa "Father Time" A: Khronos - Q: The preferred religion of Tom Cruise and John Travolta A: Scientology - Q: This god is "The Destroyer" A: Shiva - Q: The roman god/goddess for gettin down 'n' dirty A: Venus
