:doctype: book

:elixir:

= Plugs

A plug can be of two types: _module_ or _function_ A function plug is just a function A module plug is a module with two functions (`init` and `call`) and configuration They work the same

== Module Plugs

We discussed the two functions needed in the previous section

The foundation of a module plug looks like this: ``` defmodule MyPlug do   def init(opts) do     # \...
do stuff w/ options   end

def call(conn, _opts) do     # \...
manipulate the connection w/ options   end end ```

The `call` function is called at _runtime_

The `init` function is to perform any necessary heavy-lifting prep work The result of `init` is used as the second argument for `call`

In _development_ mode, `init` is called at _runtime_ In _production_ mode, `init` is called at _compile time_

== Halt

There's a function called `halt` that can be applied to a `Plug.Conn` structure to say "halt this operation" It sets the `halted` property of the structure to `true`

Plugs _automatically check_ for this `halted` property so developers don't have to add in the check themselves Nifty!
