:doctype: book

:haskell:

= Functors

A functor is a xref:./type-classes.adoc[type class] that is beneficial for dealing with values in a context.

What is meant by values in a context?
Values that are wrapped in another data type like `Maybe` or `IO` or even a list!
The types mentioned all can contain a type thus putting the child type in a context.

Functors come in handy when you want to manipulate values in a context without removing the context.
As a result you can just think about the function to be applied to the value within the context without worrying about how to deal with the context.

For a more concrete example, let's look at `Maybe` as an example.
Values of the type `Maybe` are either `Just val` or `Nothing` so any time you work with a `Maybe` type you have to code with these two possibilities in mind.
Functions to manipulate values within `Maybe` would look like this: `+ myFunc :: (a -> b) -> Maybe a -> Maybe b myFunc f Nothing = Nothing myFunc f (Just x) = Just (f x) +`

Keep in mind you'd have to do something like that for _every_ container-like data type.
`Maybe`, `IO`, `Map`, list, etc.
Functor provides this groundwork for you.

The only *function* in the typeclass is `fmap`, also represented by the operator `<$>`.
This function essentially deals with how to apply a function to a container type regardless of the many possibilities there may be within that container type.

As a small example, say you want to stringify a `Maybe Int`.
Below are two code snippets showing how to do so by making your own function and by using `fmap`: ``` myStringifyInt :: Maybe Int \-> Maybe String myStringifyInt Nothing = Nothing myStringifyInt (Just x) = show x

functorStringifyInt :: Maybe Int \-> Maybe String functorStringifyInt val = show <$> val ```

From the Data61/Nicta Course, Functor doesn't tell you much about a type outside of the ability to map over values of that type.
Functor lifts a value out of its container value.
