:doctype: book

:javascript:vue:vue-school:

= Vue.js 3 Masterclass

= Chapter 1 - Getting Started

* VueCLI is helpful for starting apps from scratch
* files/images in the _assets_ directory are processed by webpack
* `vue-cli-service` seems to be Vue's `create-react-app`

= Chapter 2 - Application Structure

* When writing components you can use `@` to represent to src directory
* Single File Template/Component = having markup, js, and css all in the one file
* There's a Vue style guide -- https://v3.vuejs.org/style-guide/#rule-categories
* CSS classes can be written as usual, no need for `className`
* it is recommended to put global styles in the root component

= Chapter 3 - Routing & Components Basics

* vue-router is similar to react-router

``` import { createRouter, createWebHistory } from 'vue-router'

const routes = [   {     path: '/',     name: 'Home',     component: Home,   } ]

const router = createRouter({   history: createWebHistory(), // There are other options too!
routes })

const App = createApp(App) App.use(router) App.mount('#app') ```

* to add an id to a route, use `/:param-name`
* you can access route info w/in a component using `this.$route`
* TODO: Look up more regarding props w/in a route object
* use `<router-link>` to link between pages
* when adding ``router-link``s, use an object with named params instead of hardcoded paths for an easier time
 ** i.e.
`<router-link :to="{ name: 'myRoute', params: { id: localVarId } }"`
* 404s: https://next.router.vuejs.org/guide/migration/#moved-the-base-option
 ** a little extra code is needed to maintain the path, query params, and any hashes in it

` next({   name: "NotFound",   params: { pathMatch: to.path.substring(1).split("/") },   query: to.query,   hash: to.hash });
`

* there are router guards to check params at different points of the navigation life cycle
 ** `beforeEnter` is an example
  *** It has the following params:
   **** `to` -- the original intended endpoint
   **** `from` -- referrer
   **** `next` -- call this function to actually nav to the other page
