:doctype: book
:pp: {plus}{plus}

:vue:

= Vuex

Vuex is a state management tool for Vue Based on Flux

Seems like Redux there's a store cannot mutate the store

Any changes you want to make to the store must be in a `mutations` property of the store You act on mutations by using `store.commit` You can add global access to the store by adding `store: store` to the initial Vue declaration Then you can access the store in components via `this.$store` Updates then would look like `this.$store.commit('name-of-mutation')`

= Accessing store from components

Access store from computed properties

The `mapState` function can be used as a shortcut from repeating `this.$store.whatever`

`+
// in vue component
export default {   computed: mapState({     thing1: state => state.thing1,     thing2: 'thing2',     derivedUsingThing3(state) {       this.somethingElse + state.thing3     }   }) } +`

= Getters

You know how with redux you'd have a util function for returning something based off of a piece of state?
Vuex has getters for this At the root store declaration you can write getter functions that get the state and do whatever with it These functions will be available to any component so you don't have to import the same file

You can access the getter via `store.getters.myFunc`

= Mutations

Mutations are like actions in Redux You have a string as a name/identifier and then you have the function ``` const store = new Vuex.store({   state: {     count: 1   },   mutations: {     increment(state) {       state.count{pp}     }   } })

store.commit('increment') ```

== Mutations with payloads

`+ mutations: {   increment(state, payload) {     ...
} } +`

== Alternate commit style

`+ store.commit({   type: 'increment',   payload: { ...
} }) +`

== Committing mutations in components

`this.$store.commit('mutation-name')`

= Actions

Similar to mutations but they trigger mutations instead of making changes to the state themselves and can be asynchronous

Each action takes a `context` parameter/arg that has the same access to `store` and `commit` but also a `dispatch` function to call other actions

== Triggering actions

`store.dispatch('action')`

== Composing actions

actions can return promises which allow you to chain actions together

= Modules

Fractal approach to the store It's like ducks!
ReDucks!
Quack

Copying the example from the docs: ``` const moduleA = {   state: () \=> ({ \...
}),   mutations: { \...
},   actions: { \...
},   getters: { \...
} }

const moduleB = {   state: () \=> ({ \...
}),   mutations: { \...
},   actions: { \...
} }

const store = new Vuex.Store({   modules: {     a: moduleA,     b: moduleB   } })

store.state.a // \-> ``moduleA``'s state store.state.b // \-> ``moduleB``'s state ```

= Modules, RootState, and TypeScript

tl;dr - type rootState as the entire state tree

_Basing this off of the source code https://github.com/vuejs/vuex/blob/dev/types/index.d.ts[here] _

The question I want answered is how to type Vuex code where `rootState` actually reflects the whole tree, as its suggested in the docs.
The https://vuex.vuejs.org/guide/modules.html#namespacing[docs] imply that rootState is how to access state outside of the current module.
This also seems to be the case on https://stackoverflow.com/questions/60120850/what-is-rootstate-in-vuejs-vuex-context[stackOverflow] Let's look at the source code.

The type for the store is: ``` export declare class Store+++<S>+++{ constructor(options: StoreOptions+++<S>+++);+++</S>++++++</S>+++

readonly state: S;
readonly getters: any;

replaceState(state: S): void;

dispatch: Dispatch;
commit: Commit;

subscribe<P extends MutationPayload>(fn: (mutation: P, state: S) \=> any, options?: SubscribeOptions): () \=> void;
subscribeAction<P extends ActionPayload>(fn: SubscribeActionOptions<P, S>, options?: SubscribeOptions): () \=> void;
watch+++<T>+++(getter: (state: S, getters: any) \=> T, cb: (value: T, oldValue: T) \=> void, options?: WatchOptions): () \=> void;+++</T>+++

registerModule+++<T>+++(path: string, module: Module<T, S>, options?: ModuleOptions): void;
registerModule+++<T>+++(path: string[], module: Module<T, S>, options?: ModuleOptions): void;+++</T>++++++</T>+++

unregisterModule(path: string): void;
unregisterModule(path: string[]): void;

hasModule(path: string): boolean;
hasModule(path: string[]): boolean;

hotUpdate(options: {     actions?: ActionTree<S, S>;
mutations?: MutationTree+++<S>+++;
getters?: GetterTree<S, S>;
modules?: ModuleTree+++<S>+++;
}): void;
} ```+++</S>++++++</S>+++

There are three things that stand out to me: - `Store<S>` - `constructor(options: StoreOptions<S>)` - `registerModule<T>(path: string, module: Module<T, S>, options?: ModuleOptions): void;`

The first is just the class.
Let's keep in mind that `<S>` is a generic, meaning it can be anything and any inner types that reference `S` will also have the properties of `S`

The second is the constructor Let's explore that type `+ export interface StoreOptions<S> {   state?: S | (() => S);
getters?: GetterTree<S, S>;
actions?: ActionTree<S, S>;
mutations?: MutationTree<S>;
modules?: ModuleTree<S>;
plugins?: Plugin<S>[];
strict?: boolean;
devtools?: boolean;
} +`

This matches how we initialize a Vuex store so that makes sense.
Here we also see a lot of `*Tree` types.
Let's check out the `ModuleTree` type, since we modularize our state through using modules

` export interface ModuleTree<R> {   [key: string]: Module<any, R>;
} `

Huh!
The type simultaneously tells us something while looking like it tells us a riddle.
Guess we have to check out `Module` now

`+ export interface Module<S, R> {   namespaced?: boolean;
state?: S | (() => S);
getters?: GetterTree<S, R>;
actions?: ActionTree<S, R>;
mutations?: MutationTree<S>;
modules?: ModuleTree<R>;
} +`

Check it out!
The type looks very similar to `StoreOptions`.
I wish the developers were a little more explicit about their types.
Through reading articles on how Vuex is used regarding `rootState` I don't think it's too farfetched to interpret `S` for `State` and `R` for `RootState`.
With this in mind we can reword the `Module` type as `Module<State, RootState>` This makes sense considering defining a module consists of two params: the relevant state and the root state.
We can see how the rootState is propagated to modules by zooming into just the module related types.
``` export interface StoreOptions+++<S>+++{ \...
modules?: ModuleTree+++<S>+++;
}+++</S>++++++</S>+++

export interface ModuleTree+++<R>+++{ [key: string]: Module<any, R>;
}+++</R>+++

export interface Module<S, R> {   \...
getters?: GetterTree<S, R>;
actions?: ActionTree<S, R>;
} ```

When we're creating a Vuex store, we're passing in a type representing some state, `S`.
That state is used in creating the `ModuleTree`.
The `ModuleTree` is a map of ``key``s, what we name our modules, and the corresponding Vuex module.
Notice how at this point, in `ModuleTree`, the values, or modules, are typed `Module<any, R>` and `ModuleTree` is referenced in `StoreOptions` as `ModuleTree<S>`.
So the `S` from `StoreOptions` becomes the `R` in the `ModuleTree`.
Sorry, this isn't worded great.
This is essentially to say the `R` in `ModuleTree`, the second param, is the `S` in `StoreOptions`.
This is important because we can see in the `ModuleType` the second param to the type, the `R`, is the `S` from the `StoreOptions`.
In other words, *the type we pass to* `StoreOptions` *is our root state*!

That's great and all from the theoretical/type sense, but what does this translate to in regards to implementation?
Let's take a moment to think about `rootState` The docs don't do a great job of describing `rootState`, but we can see an implication that `rootState` is used for accessing state outside of the current state scope in https://vuex.vuejs.org/guide/modules.html#namespacing[this part] of the docs.

I also don't think this is farfetched considering in most web apps there will be some cross-state logic.
Ideally we'd want to keep the state logic separate from the UI logic so it makes sense to keep cross-state logic within the state portion of the codebase.
That said, `rootState` then is our *entire state*.

To provide further proof of this, let's look at the typings for actions.
Within a `Module` we can see actions are typed `actions?: ActionTree<S, R>;` We know that `S` is the state related to the module and `R` is our root state.
Let's check out `ActionTree`

` export interface ActionTree<S, R> {   [key: string]: Action<S, R>;
} `

Okay.
This doesn't tell us terribly much so let's check out `Action`

`export type Action<S, R> = ActionHandler<S, R> | ActionObject<S, R>;`

Now `ActionHandler` and `ActionObject`

`+ export type ActionHandler<S, R> = (this: Store<R>, injectee: ActionContext<S, R>, payload?: any) => any;
export interface ActionObject<S, R> {   root?: boolean;
handler: ActionHandler<S, R>;
} +`

It looks like `ActionHandler` should be our focus considering it's used as the handler for `ActionObject`.
Check out the params for `ActionHandler` too `(this: Store<R>, injectee: ActionContext<S, R>, payload?: any)`

This is a bit weird.
We have to dive into the implementation to see what this is all about The file is `src/store` with the function `registerAction` `+ function registerAction (store, type, handler, local) {   const entry = store._actions[type] || (store._actions[type] = [])   entry.push(function wrappedActionHandler (payload) {     let res = handler.call(store, {       dispatch: local.dispatch,       commit: local.commit,       getters: local.getters,       state: local.state,       rootGetters: store.getters,       rootState: store.state     }, payload)     if (!isPromise(res)) {       res = Promise.resolve(res)     }     if (store._devtoolHook) {       return res.catch(err => {         store._devtoolHook.emit('vuex:error', err)         throw err       })     } else {       return res     }   }) } +`

If you zoom into the `push` function we can see the type to use `+let res = handler.call(...)+` We know that `call` is a native function that can be used to call a function with a specific `this` context This (no pun intended) makes sense considering that the first param in the type is `this` with the `Store<R>` as its type We also see the second param, `injectee` has the type `ActionContext<S, R>` We know actions have `context` as their first param And if we look at the assignment above, we can see context here has what we expect: dispatch, commit, state, rootState, etc.
`rootState` here is also just the whole state of the store!
I think this provides enough proof/assurance that rootState can be typed as our entire state
