:doctype: book

:mental-health:

= Vyvanse

Logging how i am responding to the medication

'''

2021/Jul/8 - my mind feels like a calm river - i was having a convo with a colleague over slack/IM and actually waited for a response instead of bouncing around to different apps - my leg bouncing calmed a bit, still kicked in when I was super focused on something, but I don't feel compelled to do so as often - I was on linkedIn accepting my boss' invitation, began scrolling, and was able to stop myself after 3 posts to tell myself "this isn't something I want to do" - Was in a meeting for 30 minute on a topic that doesn't super excite me but I was able to pain attention pretty dang well and take rather connected notes (still got haphazard at the end but not bad) - it's 2:32 now -- i'm wondering if it's wearing off a bit now.
I did notice my leg start shaking a lot more now.
I was still able to focus on things that weren't super interesting though (the query thing for Delilah) - 3:27pm -- i think it's still in my system.
I'm able to write smaller sentences, not run ons.
I noticed this when trying to revise my notes from earlier meeting.
- 10:17pm -- i am absolutely sure the the medication has worn off now.
I was on a 1.5 hour talk w/ Ryan and did my tangential/run-on sentence talking.
however, at the end of the work day i did find myself with more energy, not completely exhausted.
I touched my synth and was able to focus on it again.
I felt more apt to do music.
- still 10:17-ish -- Reflecting on my energy and wanting to do music makes me wonder if energy management is really key for me.
Like, do I want to do music more because I feel I have more energy?
Do I feel I have more energy because my thoughts aren't everywhere?
My meals today were okay.
Oatmeal w/ blueberries and dark chocolate for breakfast, friend's enchilada for lunch w/ a green drink (celery, spinach, kale, lime, etc.
-- i felt i needed a green), fruits and a cookie for snacks, and then brick oven pizza + mediterannean appetizers for lucnh

IDEA: Make a Haskell CLI app for logging this stuff?
But I'd probably want a UI for it.
Or maybe like a vim wiki thing for it?
Should I make a separate vimwiki for it?
A vimwiki of other vimwikis?

'''

2021/Jul/9

9:38am So far okay It's interesting, I think I can feel a switch where my brain feels less cluttered, less noisy

11:17am I felt pretty focused through finishing up the turotial for the new haskell web framework I have noticed I have dry mouth more.
I noticed a similar thing the other day but thought it was because I was thirsty and/or hungry for a snack

'''

2021/Jul/10-11

Let's talk the weekend

The weekend was interesting Saturday I felt rather tired and out of it Almost like foggy, especially mid day I thought it was just because I may not have eaten enough

Sunday was better However, I did feel rather tired again during the middle of the day

Regarding activities, we did do a lot A good mixture of chores, outside shopping for apartment stuff, meeting with friends, and walking around the park

I also fell asleep a lot sooner than I usually do, between half and hour to an hour (hour on Sunday)

'''

2021/Jul/12

MONDAY

This morning I had a _rough_ start This wasn't because of the meds though, I just got too distracted before taking them Once I took them, I felt I started feeling the vyvanse kick in a bit later than normal (which is about 15-20min) There are also tasks that I do not want to do, but can actually kind of do them I'm still procrastinating, as I am right now by writing this, but I have the other task in mind and was able to try doing a bit of work towards it

'''

2021/Jul/13

(Writing this the next morning) Yesterday was an interesting day I had a difficult problem to solve (figuring out the no sku from inputPropsMap thing) I was able to really hyperfocus on it which I can't tell how great of a thing that is I was on my lunch break and couldn't stop really thinking about it And then at the end of the day my head was feeling really busy It took me about two-ish hours to decompress

I went for a walk w/ Court after dinner We talked about home decor stuff which usually turns me off but this time I was fine!
I also played some guitar later and felt like I had a significant amount of energy as it was 11pm

'''

2021/Jul/14

Did okay this morning Had a task I was not excited for but was able to focus and get to a conclusion in 2-ish hours Right now its 2:43 and I've been procrastinating doing the thing I'm supposed to be doing A lot of leg tapping right now

'''

2021/Jul/15

I realize now I should've probably structured this log a bit more I realize morning times are a bit rough for me My head is still all over the place until the meds really cick in I'm going to try taking it first thing in the morning instead of after breakfast I also read that it might metabolize better on an empty stomach
