:doctype: book

:what-to-do:

= Car crash/accident

== Source 1 - Rothenberg Law Firm

https://www.youtube.com/watch?v=OWXhGqFJICo

. Check for injuries.
Call 911 and ask for urgent medical assistance.
Describe scenery as much as possible.
. Call police.
* Don't leave before police arrive   * Get names of all officers   * Complete a report w/ the police at the scene   * Note if the driver of the other vehicle was driving under the influence or using phone
. Get info of all things   * license plates   * car make and models + years   * insurance status of drivers
 ** if the driver is not the registered owner, get the registered owner's name, address, and phone number
. Take photos of the site, the vehicles, as soon as possible, all damage, insurance, street/environment
. Contact a lawyer (personal injury attorney) before contacting insurance company
. Notify insurance company (after talking to lawyer)
. Never talk to a representative of the other vehicle's insurance company
. Don't give any information before talking to an attorney
. Get medical care - don't neglect symptoms or pain, even if they're delayed

== Source 2 - How to Adult

Car Insurance Explained, & What to Do After a Car Accident!
https://www.youtube.com/watch?v=mRxfR2ChqNU

=== Part 1 - What is car insurance

An insurance company can help you cover your losses providing a premium is paid There are different types of coverage: - property -- car is stolen or damaged - liability -- paying others for personal or property injuries inflicted - medical -- hospital bills

=== Part 2 - Money values

Consider: - car's value - do you own the car?
- how much can you pay out of pocket?

There may be a deductible involved so it's not like you won't pay anything when getting into a crash It's the same as medical, the amount needed to pay in before it kicks in Most states require insurance

=== Part 3 - How to get insured

Insurance companies will look up credit report and your history of crashes

=== Part 4 - So you wrecked your car\...

A.k.a.
What to do when you get into an accident

. Get your car and yourself off the road and somewhere safe   * Insurance company should pay for a towing service   * Don't apologize.
It could be used against you in legal procedures
. Call the police   * Bring in a third party to document the accident   * You'll have to fill out a report
. Trade information   * other driver's name   * phone number   * make/model of car   * insurrance carrier   * address   * email   * license plate number   * insurance policy number   * request a copy of the police report   * take photos
. File a claim   * start the claim process immediately   * they should be able to  help you with everything
